name: auto-generate-gitbook
on:
  push:
    branches:
      - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: install nodejs
        uses: actions/setup-node@v1

      - name: configue gitbook
        run: |
          npm install -g gitbook-cli
          gitbook install
          npm install -g gitbook-summary

      - name: generate _book folder
        run: |
          book sm
          gitbook build
          cp SUMMARY.md _book

      - name: push _book to branch gh-pages
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO: ${{ github.repository }}
          MYEMAIL: hongaah@qq.com
          MYNAME: ${{ github.repository_owner }}
        run: |
          cd _book
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git init
          git add .
          git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
          git remote add origin https://${TOKEN}@github.com/${REPO}.git
          git push --force origin HEAD:gh-pages